sme_capital/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from control_panal import views
from control_panal.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^loans/', include('loans_app.urls', namespace='loans_app')),
    url(r'^api/loans/', include('loans_app.loan_api.urls_api', namespace='loans_api')),
    url(r'^setting/', include('control_panal.urls', namespace='control_panal')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'', views.home, name='index'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

sme_capital/control_panal/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$',  views.cms_page, name='cms_index'),  	   
]

sme_capital/loans_app/urls.py
from django.conf.urls import url
from . import views
from .views import (
	profile,
	edit_profile,
	create_loan,
	loan_list,
	loan_detail,
	loan_edit,
	loan_delete,
)


urlpatterns = [
	url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/(?P<pk>[\d+])/$', views.profile, name='pk_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
	url(r'^create/$',  views.create_loan, name='create_loan'), 
	url(r'^list/$', views.loan_list, name='list_loan'),   
	url(r'^(?P<slug>[\w-]+)/$', views.loan_detail, name='detail_loan'),   
	url(r'^(?P<slug>[\w-]+)/edit/$', views.loan_edit, name='edit_loan'),   
	url(r'^(?P<slug>[\w-]+)/delete/$', views.loan_delete, name='delete_loan'), 

	## cms  pages ##  
]

sme_capital/control_panal/models.py
from django.db import models

sme_capital/loans_app/models.py
from django.utils import timezone
import datetime
from django.conf import settings
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.db import models
from django.utils.text import slugify



class UserProfile(models.Model):
	user = models.OneToOneField(User, unique=True)
	address = models.CharField(max_length=255, blank=False)
	city = models.CharField(max_length=100)
	postcode = models.CharField(max_length=20)
	phone = models.IntegerField(unique=True)
	region = models.CharField(max_length=255)
	country = models.CharField(max_length=150)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	# manager_obj = UserProfileManager()


	def __str__(self):
		return self.user.first_name + ' ' + self.user.last_name


User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


class BusinessLoan(models.Model):
	CHOICE_RENT = (
		('rent', 'Rent'),
		('with_mortgage', 'Own with Mortgage'),
		('without_mortgage', 'Own without Mortgage'),
		('none', 'Don\'t pay rent or Mortgage')
	)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	title = models.CharField(max_length=255, blank=False, null=False)
	slug = models.SlugField(unique=True)
	amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
	start_date = models.DateField(_("Date"), default=datetime.date.today)
	end_date = models.DateField(_("Date"), default=datetime.date.today)
	repayment = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
	reference = models.CharField(max_length=12)
	phone = models.IntegerField(unique=True)
	status = models.CharField(max_length=30, choices=CHOICE_RENT, default='rent')
	created_date = models.DateTimeField(auto_now_add=True)
	updated_date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return str(self.reference)



	def get_absolute_url(self):
		return reverse("loans_app:detail_loan", kwargs={"slug": self.slug})


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = BusinessLoan.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = '%s-%s' % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_loan_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_loan_receiver, sender=BusinessLoan)

sme_capital/loans_app/forms.py
from django import forms
from django.contrib.auth.models import User 
from .models import UserProfile, BusinessLoan
from django.contrib.auth.forms import (
	UserCreationForm, 
	UserChangeForm,
)



class EditProfileForm(UserCreationForm):

	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			# 'password',
		)
		exclude = ('password',)


class BusinessLoanForm(forms.ModelForm):

	class Meta:
		model = BusinessLoan
		fields = (
			'title',
			'amount',
			'start_date',
			'end_date',
			'repayment',
			'status',
			'reference',
			'phone',
		)

sme_capital/control_panal/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
	context = {}
	return render(request, 'index.html', context)

def cms_page(request):
	context = {}
	return render(request, 'cms_index.html', context)

sme_capital/loans_app/views.py
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User 
from .models import UserProfile, BusinessLoan
from .forms import EditProfileForm, BusinessLoanForm
from django.contrib.auth.decorators import login_required


def profile(request, pk=None):

	if pk:
		user = User.objects.get(pk=pk)
	else:
		user = request.user
		
	context = {
		'user': user,
	}
	return render(request, 'backend/profile.html', context)


@login_required
def edit_profile(request):

	if request.method == 'POST':
		edit_form = EditProfileForm(request.POST, instance=request.user)

		if edit_form.is_valid():
			edit_form.save()
			update_session_auth_hash(request, edit_form.user)
			return redirect('loans_app:profile')
	else:
		edit_form = EditProfileForm(instance=request.user)
	context  = {
		'edit_form':edit_form,
	}
	return render(request, 'edit_profile.html', context)


@login_required
def create_loan(request):
	form = BusinessLoanForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		# message success
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"form": form,
	}

	return render(request, 'create_loans.html', context)


@login_required
def loan_detail(request, slug=None):
	instance = get_object_or_404(BusinessLoan, slug=slug)
	context = {
		'instance': instance,
	}
	return render(request, 'loan_detail.html', context)


@login_required
def loan_list(request):
	loans = BusinessLoan.objects.all()

	context = {
		'loans_obj': loans,
	}
	return render(request, 'loan_list.html', context)


@login_required
def loan_edit(request, slug=None):
	instance = get_object_or_404(BusinessLoan, slug=slug)
	form = BusinessLoanForm(request.POST or None, instance=instance)
	if form.is_valid():
	    instance = form.save(commit=False)
	    instance.save()
	    messages.success(request, 'The loan successfully updated!')
	    return HttpResponseRedirect(instance.get_absolute_url())
	context = {
	    'title': instance.reference,
	    'instance': instance,
	    'form': form
	}
	return render(request, 'edit_loan.html', context)

@login_required
def loan_delete(request, slug=None):
	instance = get_object_or_404(BusinessLoan, slug=slug)
	instance.delete()
	messages.success(request, 'The loan has been deleted!')
	return redirect('loans_app:list_loan')

sme_capital/control_panal/templates/cms_index.html
{% extends 'backend/back_base.html' %}


{% block content %}
<h1>Welcome home</h1>
<div class="col-md-8">
	<h3>Access the right capital solution at the right time</h3>
	<b>Let us help you achieve your strategic ambitions</b>
	<p>We will help you source the capital you need quickly, helping your business access large institutional investors committed to supporting SME growth. Our collaborative platform standardises and simplifies the loan application, ensuring a streamlined transaction process, and allowing us to focus on the core principle of lending – building a long-term relationship through understanding your business and its needs.</p>
	<br>
<br>
</div>

{% endblock content %}

sme_capital/control_panal/templates/index.html
{% extends 'base.html' %}


{% block content %}
<h1>Welcome home</h1>
<div class="col-md-8">
	<h3>Access the right capital solution at the right time</h3>
	<b>Let us help you achieve your strategic ambitions</b>
	<p>We will help you source the capital you need quickly, helping your business access large institutional investors committed to supporting SME growth. Our collaborative platform standardises and simplifies the loan application, ensuring a streamlined transaction process, and allowing us to focus on the core principle of lending – building a long-term relationship through understanding your business and its needs.</p>
	<br>
<br>
</div>

{% endblock content %}

sme_capital/loans_app/templates/create_loans.html
{% if request.user.is_staff and request.user.is_superuser %}

	{% extends 'backend/back_base.html' %}
	{% load static %}
	{% load bootstrap3 %}
	{% load bootstrap_tags %}
	{% block style %} {% endblock style %}

	{% block content %}
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<form method="POST" action='' class="form-signin">
				<h3 class="form-signin-heading text-center">Create Loans</h3>

				{% csrf_token %}
				{{form|as_bootstrap}}
				
				<button type="submit" class="btn btn-primary">Submit</button>
			</form>
			<br>
		</div>
	</div>

	{% endblock content %}

{% else %}

	{% extends 'base.html' %}
	{% load static %}
	{% load bootstrap3 %}
	{% load bootstrap_tags %}
	{% block style %} {% endblock style %}

	{% block content %}
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<form method="POST" action='' class="form-signin">
				<h3 class="form-signin-heading text-center">Create Loans</h3>

				{% csrf_token %}
				{{form|as_bootstrap}}
				
				<button type="submit" class="btn btn-primary">Submit</button>
			</form>
			<br>
		</div>
	</div>

	{% endblock content %}


{% endif %}

sme_capital/loans_app/templates/edit_loan.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}
{% load bootstrap_tags %}
{% block style %} {% endblock style %}

{% block content %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<form method="POST" class="form-signin">
			<h3 class="form-signin-heading text-center">Edit Loan</h3>

			{% csrf_token %}
			{{form|as_bootstrap}}
			
			<button type="submit" class="btn btn-primary">Update</button>
		</form>
		<br>
	</div>
</div>

{% endblock content %}

sme_capital/loans_app/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}
{% load bootstrap_tags %}
{% block style %} {% endblock style %}

{% block content %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<form method="POST" class="form-signin">
			<h3 class="form-signin-heading text-center">Update Profile</h3>

			{% csrf_token %}
			{{edit_form|as_bootstrap}}
			
			<button type="submit" class="btn btn-primary">Update</button>
		</form>
		<br>
	</div>
</div>

{% endblock content %}

sme_capital/loans_app/templates/loan_detail.html
{% extends 'base.html' %} 
 

{% block page_title %} {{instance.title}} {% endblock %} 

{% block content %}
<br>
<div class="row">
	<div class="col-md-12">
		<div class="col-md-8">
		<table class="table table-striped table-hover">
			
			<caption>
				<h3>
				<b>User Profile: </b></h3></caption>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						First Name
					</th>
					<td colspan="2" rowspan="" headers="">
						{{user.first_name}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Last Name
					</th>
					<td colspan="2" rowspan="" headers="">
						{{user.last_name}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Title
					</th>
					<td colspan="4" rowspan="" headers="">
						{{instance.title}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Amount
					</th>
					<td colspan="4" rowspan="" headers="">
						{{instance.amount}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Start Date
					</th>
					<td colspan="2" rowspan="" headers="">
						{{instance.start_date}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						End Date
					</th>
					<td colspan="4" rowspan="" headers="">
						{{instance.end_date}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Email
					</th>
					<td colspan="4" rowspan="" headers="">
						{{user.email}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Repayment
					</th>
					<td colspan="2" rowspan="" headers="">
						{{instance.repayment}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Phone
					</th>
					<td colspan="2" rowspan="" headers="">
						{{instance.phone}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Reference
					</th>
					<td colspan="4" rowspan="" headers="">
						{{instance.reference}}
					</td>
				</tr>
				
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Status
					</th>
					<td colspan="4" rowspan="" headers="">
						{{instance.status}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Publish Date
					</th>
					<td colspan="4" rowspan="" headers="">
						{{instance.created_date}}
					</td>
				</tr>
		</table>
		<hr>
	</div>
	<div class="col-md-4">
		
	</div>
	</div>
	<div class="col-md-12">
		<a href="{% url 'loans_app:create_loan' %}">
			<button type="button" class="btn btn-primary">Create New loan</button>
		</a>
		<a href="{% url 'loans_app:edit_loan' slug=instance.slug %}">
			<button type="button" class="btn btn-success">Eidt or Update</button>
		</a>
		<a href="{% url 'loans_app:delete_loan' slug=instance.slug %}">
			<button type="button" class="btn btn-danger">Delete Loan</button>
		</a>
		<a href="{% url 'loans_app:list_loan' %}">
			<button type="button" class="btn btn-warning pull-right">View all loans</button>
		</a>
		<br>
		<br>
		<hr>
	</div>

</div>
{% endblock %}

sme_capital/loans_app/templates/loan_list.html
{% extends 'base.html' %} 
{% load static %} 

{% block page_title %} {% endblock %}

{% block content %}
<div class="row">
	<br>
	<br>
	<div class="col-md-8">
		{% for loan in loans_obj %}
			<h3><b>Full Name:</b> {{request.user.first_name}} {{request.user.last_name}}</h3>

			<p class="lead"><b>Loan Title:</b> {{loan.title}}</p>
			<p class="lead"><b>Amount:</b> {{loan.amount}}</p>
			<p class="lead"><b>Reference:</b> {{loan.reference}}</p>
			<p class="lead"><b>Created Date:</b> {{loan.created_date}}</p>

			<a href="{% url 'loans_app:detail_loan' slug=loan.slug %}">
				<button type="button" class="btn btn-primary pull-right readmore">
					More detail
				</button>
			</a>
		<hr>		
		{% endfor %}
	</div>
	<div class="col-md-4">
		
	</div>
	{% if request.title.id is None %}
	<div class="col-md-12">
				
		<a href="{% url 'loans_app:create_loan' %}">
			<button type="button" class="btn btn-success pull-right">Create New loan</button>
		</a>
	</div>
	{% else %}
	{% endif %}
</div>
<br><br>
{% endblock %}

sme_capital/loans_app/templates/profile.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<table class="table table-striped table-hover">
			
			<caption><h3>{{request.user.username.upper}} Profile</h3></caption>
				<div class="useravatar">
					{% if user.userprofile.image %}
						<img src="{{user.userprofile.image.url}}" width="250" height="200">
					{% endif %}
				</div>
				<br>
				<ul class="nav nav-tab nav-menu" role='tablist'>
					<li class="active">
						<a class="btn btn-primary" href="{% url 'loans_app:profile' %}" data-toddle='tab'>
							<i class=" fa fa-male"> Profile</i>
						</a>
					</li>
					<br>
					
				</ul>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						First Name
					</th>
					<td colspan="2" rowspan="" headers="">
						{{user.first_name}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Last Name
					</th>
					<td colspan="2" rowspan="" headers="">
						{{user.last_name}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Address 1
					</th>
					<td colspan="4" rowspan="" headers="">
						{{user.userprofile.address}}
					</td>
				</tr>
				
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						City
					</th>
					<td colspan="2" rowspan="" headers="">
						{{user.userprofile.city}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Post Code
					</th>
					<td colspan="4" rowspan="" headers="">
						{{user.userprofile.postcode}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Email
					</th>
					<td colspan="4" rowspan="" headers="">
						{{user.email}}
					</td>
				</tr>
				<tr>
					<th colspan="3" rowspan="" headers="" scope="">
						Phone
					</th>
					<td colspan="2" rowspan="" headers="">
						{{user.userprofile.phone}}
					</td>
				</tr>		
				
		</table>
		<ul class="nav nav-tab nav-menu" role='tablist'>
			<li>
				<a class="btn btn-success" 
				href="{% url 'loans_app:edit_profile' %}" data-toddle='tab'>
					<i class=" fa fa-key">Edit Profile</i>
				</a>
			</li>
		</ul>
		<br>
	</div>
	
</div>
{% endblock content %}

sme_capital/templates/backend/back_base.html
{% load static %}
{% load bootstrap_tags %}
{% block style %} {% endblock style %}

{% include 'backend/back_header.html' %}
{% include 'backend/back_navbar.html' %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active text-center">
                    <a href="{% url 'index' %}">
                        Home
                    </a>
                    <span class="sr-only">(current)</span></a>
                </li>
                <li class="text-center"><a href="{% url 'loans_app:list_loan' %}">Loans</a>
                <li class="text-center"><a href="{% url 'loans_api:list_api' %}">API</a>
                </li>

            </ul>
        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
            <h1 class="page-header">CMS</h1>
        </div>
          {# include 'backend/messages.html' #}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
          {% block content %}

          {% endblock content %}

        </div>
    </div>
</div>
  
    {% include 'backend/back_footer.html' %}

sme_capital/templates/backend/back_footer.html
{% load staticfiles %}
    
    <footer class="container-backend col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
        <div class="row backend">
            <div class="col-md-4 ">
                <ul>
                    <li>Home</li>
                    <li>About</li>
                    <li>Contact</li>
                </ul>
            </div>
            <div class="col-md-4 ">
                <p class="text-center">Term and Condtion</p>
            </div>
            <div class="col-md-4 ">
                <ul>
                    <li>Facebook</li>
                    <li>Twitter</li>
                    <li>LinkedIn</li>
                </ul>
            </div>
        </div>
        
    </footer>

<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'bootstrap/js/vendor/holder.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'bootstrap/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

sme_capital/templates/backend/back_navbar.html
{% load staticfiles %}

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">SME CAPITAL</a>
    </div>
    
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'control_panal:cms_index' %}">Dashboard</a></li>
        <li><a href="#">Settings</a></li>
        <li><a href="{% url 'loans_app:profile' %}"> Profile</a></li>
        <li><a href="#">Help</a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form>
    </div>
  </div>
</nav>

sme_capital/templates/base.html
{% include 'header.html' %}
{% include 'navbar.html' %}


<div class="container">
{% block content %}
	
{% endblock content %}
</div>
{% include 'footer.html' %}	

sme_capital/templates/footer.html
{% load static %}

    
    </div> <!-- /container -->
    
    <footer class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <ul>
                    <li>Home</li>
                    <li>About</li>
                    <li>Contact</li>
                </ul>
            </div>
            <div class="col-md-4">
                <p class="text-center">Term and Condtion</p>
            </div>
            <div class="col-md-4">
                <ul>
                    <li>Facebook</li>
                    <li>Twitter</li>
                    <li>LinkedIn</li>
                </ul>
            </div>
        </div>
        
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'bootstrap/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

sme_capital/templates/navbar.html
{% load static %}

{% load staticfiles %}
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">
        <strong>
          SME CAPITAL
        </strong>
      </a>
    </div>

    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'loans_app:list_loan' %}">Loan</a></li>

        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> API<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <a href="{% url 'loans_api:list_api' %}" title=""> API list
              </a>
            </li>
            
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
          
       <li class="dropdown">
        {% if request.user.is_authenticated and not '/accounts/login' in request.get_full_path %}
         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{request.user.username.upper}} <span class="caret"></span>
            <i class=""></i> 
          </a>
            <!-- Nor mal user can have acces to own profile only -->
            <ul class="dropdown-menu">
            {% if not request.user.is_staff %}
              <li>
                <a href="{% url 'loans_app:profile' %}">
                  <i class="fa fa-user"></i> Profile
                </a>
              </li>
            {% endif %}
            <!-- End of basic user -->

            <!-- user from the company can have access to cms page where can view create update and delete forms has been created -->
              {% if request.user.is_staff %}
              <li><a href="{% url 'control_panal:cms_index' %}" target="_blank">
                <i class="fa fa-tasks"></i> CMS
              </a></li>
              <li>
                <a href="{% url 'loans_app:profile' %}">
                  <i class="fa fa-user"></i> Profile
                </a>
              </li>
              {% endif %}
              <li><a href="{% url 'auth_password_change' %}">
                <i class="fa fa-unlock-alt"></i> Change Password
              </a></li>
              <li><a href="{% url 'auth_logout' %}">
                <i class="fa fa-sign-out"></i> Logout
              </a></li>
            </ul>
        </li>
        {% else %}
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Account <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'auth_login' %}" title=""><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a></li>
          <li><a href="{% url 'auth_password_reset' %}">
            <i class="fa fa-unlock"></i> Forgot Password</a></li>
          <li><a href="{% url 'registration_register' %}">
          <i class="fa fa-registered"></i> Register</a></li>
        </ul>
      </li>
      {% endif %}
      </ul>

    </div><!--/.nav-collapse -->

  </div>
</nav>